[window.dimensions]
# columns = 150
# lines = 40

[cursor]
# カーソルを点滅させる
style = { blinking = "On" }
# 点滅のインターバル
blink_interval = 500
# 点滅を停止するまでの秒数（0: 停止しない）
blink_timeout = 0

[font]
size = 12.5

[font.normal]
family = "HackGen Console NF"
