[settings]
experimental = true
disable_backends = ["asdf", "vfox"]

[settings.pipx]
uvx = true

[tools]
chezmoi = "latest"
yazi = "latest"
uv = "latest"
neovim = "latest"
ruff = "latest"
"github:trasta298/keifu" = "latest"
node = "latest"
jq = "latest"
rust-analyzer = "latest"
github-cli = "latest"
opencode = "latest"
rust = "latest"
cargo = "latest"

